"""Generate fake-but-consistent person records for demos and load testing.

Privacy (plan §12): names come from a small internal dictionary (never real
people), cédulas use the reserved fake range V-00500000..V-00999999 (offset from
``egi seed`` so the two never collide), and every row is tagged TEST DATA. Status
is weighted to look like a real disaster distribution. Generation is deterministic
(seeded RNG) so ``--dry-run`` previews exactly what a real run would create.
"""

import random
import uuid
from typing import Optional

from models import now_iso

# Internal name dictionary — obviously generic, not real individuals.
GIVEN_NAMES = [
    "María", "José", "Carmen", "Luis", "Ana", "Pedro", "Rosa", "Carlos",
    "Juana", "Miguel", "Elena", "Jesús", "Gloria", "Rafael", "Teresa", "Andrés",
]
FAMILY_NAMES = [
    "Pérez", "Rodríguez", "González", "Martínez", "Hernández", "Sánchez",
    "Díaz", "Ramírez", "Torres", "Flores", "Rivas", "Mendoza", "Castro", "Ruiz",
]
FALLBACK_CITIES = ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "La Guaira", "Mérida"]

# (status, weight) — roughly disaster-shaped.
STATUS_WEIGHTS = [
    ("missing", 0.45), ("sighted", 0.15), ("found", 0.15),
    ("safe", 0.15), ("care", 0.07), ("deceased", 0.03),
]

# Reserved synthetic cédula sub-range start (still inside V-00xxxxxx fake range).
CEDULA_START = 500000
CEDULA_MAX = 999999
SYNTH_SOURCE = "synthetic"
SYNTH_PROVENANCE = "TEST DATA — NOT REAL — generated by egi generate-synthetic"
# Fixed seed → deterministic preview == actual output.
RNG_SEED = 20260315


def _weighted_status(rng: random.Random) -> str:
    r = rng.random()
    cum = 0.0
    for status, w in STATUS_WEIGHTS:
        cum += w
        if r <= cum:
            return status
    return STATUS_WEIGHTS[0][0]


def generate_persons(disaster_id: Optional[str] = None, count: int = 20,
                     dry_run: bool = False) -> dict:
    """Generate ``count`` synthetic persons. Skips any cédula already present.

    Returns ``{"created": int, "skipped": int, "preview": [ {id,name,status,cedula,...} ]}``.
    In dry-run mode nothing is written; ``preview`` still lists what would be created.
    """
    import db

    db.init_db()
    rng = random.Random(RNG_SEED)

    with db.get_db() as conn:
        existing = {
            row[0] for row in conn.execute(
                "SELECT cedula FROM persons WHERE cedula IS NOT NULL"
            ).fetchall()
        }
        cities = [r[0] for r in conn.execute(
            "SELECT name FROM cities ORDER BY created_at"
        ).fetchall()] or FALLBACK_CITIES

    preview = []
    rows = []
    skipped = 0
    n = 0
    cedula_n = CEDULA_START
    now = now_iso()
    while len(rows) < count and cedula_n <= CEDULA_MAX:
        cedula = f"V-{cedula_n:08d}"
        cedula_n += 1
        if cedula in existing:
            skipped += 1
            continue
        n += 1
        given = rng.choice(GIVEN_NAMES)
        family = rng.choice(FAMILY_NAMES)
        name = f"{given} {family} (PRUEBA)"
        status = _weighted_status(rng)
        location = rng.choice(cities)
        person = {
            "id": f"egi-synth-{uuid.uuid4().hex[:8]}",
            "disaster_id": disaster_id,
            "name": name,
            "given_name": given,
            "family_name": f"{family} (PRUEBA)",
            "cedula": cedula,
            "status": status,
            "sex": "F" if given.endswith("a") else "M",
            "age": rng.randint(1, 90),
            "location": location,
            "last_known_location": location,
            "source": SYNTH_SOURCE,
            "provenance": SYNTH_PROVENANCE,
            "reviewed": 0,
            "created_at": now,
            "updated_at": now,
        }
        rows.append(person)
        preview.append({"id": person["id"], "name": name, "status": status, "cedula": cedula})

    created = 0
    if not dry_run and rows:
        with db.get_db() as conn:
            for person in rows:
                columns = ", ".join(person.keys())
                placeholders = ", ".join(f":{k}" for k in person.keys())
                conn.execute(
                    f"INSERT OR REPLACE INTO persons ({columns}) VALUES ({placeholders})",
                    person,
                )
            conn.commit()
        created = len(rows)

    return {"created": created, "skipped": skipped, "preview": preview}
