#!/usr/bin/env node
// `npm run ux:audit` — the one-command UX pre-flight (plan-29 §2). It runs the
// no-dependency static checks the repo already trusts and writes a dated
// markdown report under docs/ux-audit/reports/, so a single developer can audit
// before a release without a QA team or network access:
//
//   1. i18n language purity + key parity  (scripts/i18n-check.js)
//   2. WCAG contrast over design tokens    (scripts/ux-contrast.mjs)
//   3. Offline self-containment of dist/   (scripts/check-offline-assets.mjs, if built)
//
// Heavier, optional tools (Lighthouse, axe, Playwright) are documented in
// docs/ux-audit/PREFLIGHT_CHECKLIST.md and exposed as separate opt-in npm
// scripts; they need network/extra deps so they are not part of this default
// run. The automated accessibility unit check runs under `npm test`
// (tests/a11y.test.js) and is what CI gates on.

import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const frontend = join(here, '..')
const repo = join(frontend, '..')
const reportsDir = join(repo, 'docs', 'ux-audit', 'reports')

function run(cmd, args) {
  try {
    const out = execFileSync(cmd, args, { cwd: frontend, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
    return { ok: true, out }
  } catch (e) {
    return { ok: false, out: (e.stdout || '') + (e.stderr || '') || String(e) }
  }
}

const results = {}

// 1. i18n
results.i18n = run('node', ['scripts/i18n-check.js'])

// 2. contrast (machine-readable)
const contrast = run('node', ['scripts/ux-contrast.mjs', '--json'])
let contrastRows = []
try { contrastRows = JSON.parse(contrast.out) } catch { /* keep raw */ }

// 3. offline assets (only meaningful once dist/ exists)
const builtDist = existsSync(join(frontend, 'dist'))
results.offline = builtDist ? run('node', ['scripts/check-offline-assets.mjs']) : null

// ----- Build the report -----
const lines = []
lines.push('# EGI UX audit report')
lines.push('')
lines.push('> Generated by `npm run ux:audit` (plan-29 §2). Static, no-network checks.')
lines.push('')

lines.push('## 1. Internationalization')
lines.push('')
lines.push('```')
lines.push(results.i18n.out.trim() || '(no output)')
lines.push('```')
lines.push('')

lines.push('## 2. Color contrast (WCAG 2.1 AA over design tokens)')
lines.push('')
if (contrastRows.length) {
  lines.push('| Result | Ratio | Need | Pair |')
  lines.push('| --- | --- | --- | --- |')
  for (const r of contrastRows) {
    const flag = r.pass ? '✅ pass' : (r.critical ? '❌ FAIL' : '⚠️ warn')
    lines.push(`| ${flag} | ${r.ratio}:1 | ${r.need} | ${r.name} |`)
  }
  const warns = contrastRows.filter((r) => !r.pass && !r.critical)
  const fails = contrastRows.filter((r) => !r.pass && r.critical)
  lines.push('')
  lines.push(`**${fails.length} critical fail(s), ${warns.length} warning(s).** Warnings are below AA but not release-gated — track them in a findings doc and prefer them for large/secondary text only.`)
} else {
  lines.push('```')
  lines.push(contrast.out.trim())
  lines.push('```')
}
lines.push('')

lines.push('## 3. Offline self-containment (built PWA)')
lines.push('')
if (!builtDist) {
  lines.push('_Skipped — `dist/` not built. Run `npm run build` then re-run to verify no font/CDN requests leak into the offline bundle._')
} else {
  lines.push('```')
  lines.push(results.offline.out.trim() || '(no output)')
  lines.push('```')
}
lines.push('')

lines.push('## Next steps')
lines.push('')
lines.push('- Complete the manual checklist: `docs/ux-audit/PREFLIGHT_CHECKLIST.md`.')
lines.push('- Optional deep audits (need network / extra deps): `npm run ux:lighthouse`, `npm run ux:axe`.')
lines.push('- File anything new in `docs/ux-audit/findings-NNN.md`.')
lines.push('')

const report = lines.join('\n')

// Write a dated report. The date comes from the environment, not Date.now in a
// pinned context — but this is a CLI run, so a wall-clock stamp is fine here.
mkdirSync(reportsDir, { recursive: true })
const stamp = new Date().toISOString().slice(0, 10)
const file = join(reportsDir, `ux-audit-${stamp}.md`)
const latest = join(reportsDir, 'latest.md')
writeFileSync(file, report)
writeFileSync(latest, report)

// Console summary
console.log(report)
console.log(`\n[ux-audit] report written to docs/ux-audit/reports/ux-audit-${stamp}.md (and latest.md)`)

// Exit non-zero only if i18n purity broke (the one hard gate); contrast/offline
// are advisory in the default run.
process.exit(results.i18n.ok ? 0 : 1)
