"""Fixture-driven seeding for EGI (mirrors CalorIA's seed.py approach).

All generated rows use the deterministic id prefix ``egi-seed-`` and persons/
reports also set ``source='seed'``, so ``remove_seeded_data()`` is exact and
reversible. Every person/report is tagged with an obviously-fake name and a
``TEST DATA — NOT REAL`` provenance string (plan §3). Timestamps are fixed and
deterministic so re-seeding is idempotent (INSERT OR REPLACE on stable ids).
"""

import json
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

SEED_PREFIX = "egi-seed-"
SEED_SOURCE = "seed"
SEED_PROVENANCE = "TEST DATA — NOT REAL — generated by egi seed"
# Fixed, deterministic timestamp for all seeded rows (idempotent re-seeds).
SEED_TS = "2026-03-15T12:00:00Z"

# Tables that hold seeded rows, in dependency-safe deletion order.
SEEDED_TABLES = ("reports", "persons", "incidents", "cities", "events")


def _load(name: str) -> list:
    with open(FIXTURES_DIR / name, encoding="utf-8") as f:
        return json.load(f)


def _test_cedula(n: int) -> str:
    """A cédula in the reserved fake range V-00000000..V-00999999 (plan §12)."""
    return f"V-{n:08d}"  # n stays well under 1_000_000 in practice


def seed_database(disaster_id=None, person_count: int = 20, report_count: int = 10) -> dict:
    """Seed events, cities, incidents, persons and reports as TEST DATA.

    Person/report templates are cycled to reach the requested counts; ids are
    deterministic (``egi-seed-person-001`` …) so unseed is exact. Returns a
    summary dict of how many rows of each kind were written.
    """
    import db

    db.init_db()
    events = _load("events.json")
    cities = _load("cities.json")
    incidents = _load("incidents.json")
    person_templates = _load("persons.json")
    report_templates = _load("reports.json")

    city_by_id = {c["id"]: c for c in cities}
    event_tag_by_id = {e["id"]: e.get("tag") for e in events}

    counts = {"events": 0, "cities": 0, "incidents": 0, "persons": 0, "reports": 0}

    with db.get_db() as conn:
        cur = conn.cursor()

        for e in events:
            cur.execute(
                """INSERT OR REPLACE INTO events
                   (id, name, region, type, tag, date, status, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (e["id"], e.get("name"), e.get("region"), e.get("type"), e.get("tag"),
                 e.get("date"), e.get("status"), SEED_TS, SEED_TS),
            )
            counts["events"] += 1

        for c in cities:
            cur.execute(
                """INSERT OR REPLACE INTO cities
                   (id, event_id, name, region, lat, lon, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (c["id"], c.get("event_id"), c.get("name"), c.get("region"),
                 c.get("lat"), c.get("lon"), SEED_TS, SEED_TS),
            )
            counts["cities"] += 1

        for inc in incidents:
            cur.execute(
                """INSERT OR REPLACE INTO incidents
                   (id, event_id, kind, title, description, lat, lon, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (inc["id"], inc.get("event_id"), inc.get("kind"), inc.get("title"),
                 inc.get("description"), inc.get("lat"), inc.get("lon"), SEED_TS, SEED_TS),
            )
            counts["incidents"] += 1

        person_ids = []
        for i in range(person_count):
            tpl = person_templates[i % len(person_templates)]
            pid = f"{SEED_PREFIX}person-{i + 1:03d}"
            city = city_by_id.get(tpl.get("city_id"))
            location = city["name"] if city else None
            did = disaster_id or (event_tag_by_id.get(city["event_id"]) if city else None)
            given = tpl.get("given_name")
            family = tpl.get("family_name")
            name = " ".join(p for p in (given, family) if p)
            cur.execute(
                """INSERT OR REPLACE INTO persons
                   (id, disaster_id, name, status, gender, age, location, clothes, notes,
                    source, provenance, reviewed, given_name, family_name, cedula, sex,
                    last_known_location, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (pid, did, name, tpl.get("status"), None, tpl.get("age"), location,
                 tpl.get("clothes"), tpl.get("notes"), SEED_SOURCE, SEED_PROVENANCE, 1,
                 given, family, _test_cedula(i + 1), tpl.get("sex"), location,
                 SEED_TS, SEED_TS),
            )
            person_ids.append(pid)
            counts["persons"] += 1

        for j in range(report_count):
            if not person_ids:
                break
            tpl = report_templates[j % len(report_templates)]
            rid = f"{SEED_PREFIX}report-{j + 1:03d}"
            person_id = person_ids[j % len(person_ids)]
            cur.execute(
                """INSERT OR REPLACE INTO reports
                   (id, person_id, author_name, author_relation, status, note, location,
                    source, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (rid, person_id, tpl.get("author_name"), tpl.get("author_relation"),
                 tpl.get("status"), tpl.get("note"), tpl.get("location"),
                 SEED_SOURCE, SEED_TS, SEED_TS),
            )
            counts["reports"] += 1

        conn.commit()

    return counts


def remove_seeded_data(dry_run: bool = False) -> dict:
    """Remove all seeded rows (deterministic ``egi-seed-`` ids; persons/reports
    also matched by ``source='seed'``). Manually-created rows are never touched.

    With ``dry_run=True`` it only counts what would be deleted. Returns a summary
    dict keyed by table name.
    """
    import db

    db.init_db()
    counts = {}
    with db.get_db() as conn:
        cur = conn.cursor()
        for table in SEEDED_TABLES:
            # persons/reports carry an explicit source marker; all tables share
            # the id prefix, which is the authoritative, reversible marker.
            if table in ("persons", "reports"):
                where = "id LIKE ? OR source = ?"
                params = (f"{SEED_PREFIX}%", SEED_SOURCE)
            else:
                where = "id LIKE ?"
                params = (f"{SEED_PREFIX}%",)
            n = cur.execute(
                f"SELECT COUNT(*) FROM {table} WHERE {where}", params
            ).fetchone()[0]
            counts[table] = n
            if not dry_run and n:
                cur.execute(f"DELETE FROM {table} WHERE {where}", params)
        if not dry_run:
            conn.commit()
    return counts
