"""Structured logging + request-scoped tracing (plan-15 §5).

In production EGI logs one JSON object per line so the output can be shipped to
Loki / Datadog / CloudWatch with no regex parsing. In development it falls back
to a human-readable text format. A request-scoped ``request_id`` (generated by
the access middleware, or echoed from an inbound ``X-Request-ID``) is injected
into every log record via a contextvar, so a failed login or moderation action
can be traced end-to-end by one id.

Privacy (plan-15 §14): the access log records method/path/status/duration and an
optional ``user_id`` — never bearer tokens, passwords, or record content. Paths
may contain ids (they are URLs), which is acceptable in an operator-only log but
NEVER in a metric label (see metrics.py).
"""

import json
import logging
import os
import sys
from contextvars import ContextVar

# Request-scoped trace id. Empty string when outside a request (e.g. CLI, boot).
request_id_var: ContextVar[str] = ContextVar("request_id", default="")

# Standard LogRecord attributes we should not duplicate into the JSON "extra"s.
_RESERVED = set(
    logging.makeLogRecord({}).__dict__.keys()
) | {"message", "asctime", "taskName"}


class RequestIdFilter(logging.Filter):
    """Attach the current request_id (if any) to every record."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = request_id_var.get("")
        return True


class JsonFormatter(logging.Formatter):
    """Render a LogRecord as a single-line JSON object."""

    def format(self, record: logging.LogRecord) -> str:
        payload = {
            "timestamp": self.formatTime(record, "%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        rid = getattr(record, "request_id", "")
        if rid:
            payload["request_id"] = rid
        # Merge any structured extras passed via logger.info(..., extra={...}).
        for key, value in record.__dict__.items():
            if key not in _RESERVED and key not in payload and not key.startswith("_"):
                payload[key] = value
        if record.exc_info:
            payload["exc_info"] = self.formatException(record.exc_info)
        return json.dumps(payload, ensure_ascii=False, default=str)


def _log_format() -> str:
    """'json' (default in production) or 'text' (default in development)."""
    fmt = os.environ.get("LOG_FORMAT", "").strip().lower()
    if fmt in ("json", "text"):
        return fmt
    env = os.environ.get("ENV", "production").strip().lower()
    return "text" if env == "development" else "json"


def configure_logging() -> None:
    """Install the chosen formatter + request-id filter on the root logger.

    Idempotent: replaces existing handlers so repeated calls (tests, reload) do
    not stack duplicate output.
    """
    level_name = os.environ.get("LOG_LEVEL", "INFO").strip().upper()
    level = getattr(logging, level_name, logging.INFO)

    handler = logging.StreamHandler(sys.stdout)
    handler.addFilter(RequestIdFilter())
    if _log_format() == "json":
        handler.setFormatter(JsonFormatter())
    else:
        handler.setFormatter(
            logging.Formatter(
                "%(asctime)s %(levelname)s %(name)s [%(request_id)s] %(message)s"
            )
        )

    root = logging.getLogger()
    root.handlers = [handler]
    root.setLevel(level)
    # Route uvicorn's access/error logs through our handler too (no double lines).
    for name in ("uvicorn", "uvicorn.error", "uvicorn.access"):
        lg = logging.getLogger(name)
        lg.handlers = []
        lg.propagate = True
